name: Bump Version and Push Tag

on:
  push:
    branches:
      - main

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Update version file
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          # Get the current version from version.txt
          current_version=$(cat version.txt)
          # Check if the latest tag is different from the current version
          if [ "$latest_tag" != "$current_version" ]; then
            echo "Changing version.txt from $current_version to $latest_tag"
            # Write to version.txt file
            echo "$latest_tag" > version.txt
          else
            echo "The latest tag is the same as the current version. No update needed."
          fi

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          # Disable exit-on-error mode:
          # set +e
          git add CHANGELOG.md version.txt
          git status
          git commit --verbose -m "Update changelog"
          git status
          git fetch origin
          git rebase --strategy-option=theirs origin/main --verbose
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
